services:
  - type: web
    name: linkedin-scraper
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyD8sY5E0dj-6yKyXjqaGH3a5CSQYEdI4yo 