services:
  - type: web
    name: linkedin-scraper
    env: python
    buildCommand: |
      chmod +x setup.sh
      ./setup.sh
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GOOGLE_API_KEY
        value: AIzaSyD8sY5E0dj-6yKyXjqaGH3a5CSQYEdI4yo
      - key: CHROME_BIN
        value: /usr/bin/chromium-browser 