services:
  - type: web
    name: linkedin-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.enableCORS false
    autoDeploy: false
    envVars:
      - key: GOOGLE_API_KEY
        value: YOUR_GEMINI_API_KEY_HERE
